server:
  port: 3333

spring:
  application:
      name: customer
  cloud:
      config:
        discovery:
          enabled: false
          serviceId: customer
        label: master
        profile: pre
      consul:
        host: http://localhost:8500
        port: 80
        discovery:
            prefer-ip-address: true
            health-check-path: /actuator/health
            heartbeat:
              enabled: false
            health-check-interval: 2s



